FROM golang:alpine
RUN apk update && apk add netcat-openbsd

WORKDIR /build/

COPY go.mod .
COPY go.sum .
# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

COPY . .
ENV GOOS=linux \
    GOARCH=386 \
    POSTGRES_MIGRATIONS_PATH=file:///build/db/migrations/

