version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bike
    ports:
    - 5432:5432

  db-test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: bike_test

  tests:
    build:
      context: ./
      dockerfile: Dockerfile-tests
    environment:
      POSTGRES_TEST_URL: postgres://postgres:test@db-test:5432/bike_test?sslmode=disable
    command: sh -c 'while ! nc -z db-test 5432; do sleep 1; done; go test -v -vet=off ./...'

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: postgres://postgres:test@db:5432/bike?sslmode=disable
      FIXTURES: 'true'
    ports:
    - 8080:8080
    command: sh -c 'while ! nc -z db 5432; do sleep 1; done; /app/bike'